# Generated by Django 3.1 on 2020-10-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNum', models.CharField(max_length=11)),
                ('caseType', models.CharField(max_length=50)),
                ('incDate', models.DateField()),
                ('invName', models.CharField(max_length=255)),
                ('invLname', models.CharField(max_length=255)),
                ('streetNum', models.CharField(max_length=50)),
                ('streetNam', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfapp.user')),
            ],
        ),
    ]
